### ISSUE TITLE
Add Funding.yaml

### ISSUE THREAD

**Issue by PedroHase** [SeriousOldMan/Simulator-Controller#13]
Hey, first of all this is an awesome tool and thank you for open-sourcing this!

To better support you, I'd like to suggest adding a [funding.yml](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) so your Patreon and Paypal would be more prominently displayed.

Example `funding.yaml`

```yaml
patreon: simulatorcontroller
custom: https://www.paypal.com/donate/?hosted_button_id=7GV86ZPS95SL6
```

Cheers, and keep up the great work!

**Comment by SeriousOldMan** [comment]
Thx for the hint. Have set it up...
