### ISSUE TITLE
Starting Simulator Configuration

### ISSUE THREAD

**Issue by cradman1979** [SeriousOldMan/Simulator-Controller#7]
Hello,

I have just installed the software but when I run the "simulator configuration.exe" it tells me :

Error while initializing speech recognition module - please check configuration
No languages found while initializing speech recognition system - please check configuration

I am running windows 10 and I am hoping to use this software for pitstops while in VR. Could you help please?

Thanks in advance

**Comment by SeriousOldMan** [comment]
Hi,

you might want to take a look here: [Unblock the applications for Windows](https://github.com/SeriousOldMan/Simulator-Controller/wiki/Installation-&-Configuration#installation)

and here: [Installation of languages for Voice Interaction](https://github.com/SeriousOldMan/Simulator-Controller/wiki/Virtual-Race-Engineer#installation)

It looks like your Windows installation is missing some of the voice recognition and generation components or cannot access them.

Cheers

Oliver

**Comment by cradman1979** [comment]
Hi Oliver,

Thanks for replying.

I didn't have any file blocked errors detected by windows that I could tell but I ran the commands from the powershell script anyway.

In settings I have the English language pack installed under settings>language>preferred languages 
and under settings>speech>installed voice packages it shows English UK and US.

Any other ideas please?

Thanks,

Adam

**Comment by SeriousOldMan** [comment]
Yes, but the system is asking for **recognition** languages. You will find in the Utilities\3rd Party folder some Microsoft installer for the Voice recognition runtime, which is not installed on every Windows system.

**Comment by cradman1979** [comment]
Ok thanks so I have run the speechplatformruntime.msi and no more errors but it minimises to the taskbar and the config screen doesn't actually open. 

Sorry to bother you with this

**Comment by SeriousOldMan** [comment]
Did you also install one of the language packs, that are also included in this folder? The runtime alone is not enough...

**Comment by cradman1979** [comment]
Ah there it is. Ran the MSSpeech_SR_en-US_TELE.msi and now the configurator opens. Thanks for that. I didn't want to go blindly clicking on everything. Now for the fun of making it work with ACC and my VR setup :)

**Comment by SeriousOldMan** [comment]
Great, feel free to return, if you have anything else. You may want to use the Discussion though....
