### ISSUE TITLE
Please restore all author comments on code from Crew Chief and RF2SMMP

### ISSUE THREAD

**Issue by TheIronWolfModding** [SeriousOldMan/Simulator-Controller#8]
Please restore all author comments on code from Crew Chief and RF2SMMP.  CC is under MIT and RF2SMMP is under GPL2.  This code was a lot of work and comments were put there to be kept on reuse.

**Comment by SeriousOldMan** [comment]
No probs. There are still a lot of Kudos to you and crew chief in the (modified) code, the README file and the original license is part of the License file. Anyway, will be done with the next scheduled release by the end of next week.

Cheers, Oliver

**Comment by SeriousOldMan** [comment]
Done for MappedBuffer.cs and rf2Data.cs. Take a look at the development branch. Hope, your fine now.

Regards, Oliver
