### ISSUE TITLE
Antivirus issue: IDP.HELU.PSD11

### ISSUE THREAD

**Issue by aderrs003** [SeriousOldMan/Simulator-Controller#9]
I use AVG antivirus and when installing, it comes up with the above detection as can be seen in the image
![Capture](https://user-images.githubusercontent.com/48966327/146335650-b4b0606f-e021-4d70-94cf-c35c0b2bfd55.PNG)

**Comment by aderrs003** [comment]
I just read the description please ignore

**Comment by BeatDeath** [comment]
I find the same problem but the process that I have to start is part of a verified installation that took place from a reliable source, then why does it detect that there is a threat?

**Comment by SeriousOldMan** [comment]
There is definitely no virus in there. The underlying programming language is unfortunately not in very widespread use and I have not bought a certificate for signing the binaries.

 

Von: ▅▇█▓▒░☠BeatDeath☠░▒▓█▇▅ ***@***.***> 
Gesendet: Samstag, 11. Februar 2023 16:19
An: SeriousOldMan/Simulator-Controller ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [SeriousOldMan/Simulator-Controller] Antivirus issue: IDP.HELU.PSD11 (Issue #9)

 

I find the same problem but the process that I have to start is part of a verified installation that took place from a reliable source, then why does it detect that there is a threat?
